apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: three-tier-app-prod
  namespace: argocd
spec:
  project: three-tier-gitops

  source:
    repoURL: https://dev.azure.com/RajeshPatibandla1987/three-tier-azure-gitops/_git/three-tier-gitops-app
    targetRevision: main
    path: k8s/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: three-tier-app

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
